// <auto-generated />
using System;
using ControleArquivosGEADI.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleArquivosGEADI.API.Migrations
{
    [DbContext(typeof(ControleDboContext))]
    [Migration("20240917202228_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb001ControleArquivo", b =>
                {
                    b.Property<long>("NuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("nu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NuId"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime>("DtLog")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_log");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_modificacao");

                    b.Property<string>("NoArquivo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("no_arquivo");

                    b.Property<string>("NoLocal")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("no_local");

                    b.Property<long>("NuLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("nu_lote_id");

                    b.Property<long>("QtBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("qt_bytes");

                    b.HasKey("NuId");

                    b.HasIndex(new[] { "NuLoteId" }, "IX_aditb001_controle_arquivos_nu_lote_id");

                    b.ToTable("aditb001_controle_arquivos", (string)null);
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb002LoteArquivo", b =>
                {
                    b.Property<long>("NuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("nu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NuId"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("QtArquivos")
                        .HasColumnType("int")
                        .HasColumnName("qt_arquivos");

                    b.HasKey("NuId");

                    b.ToTable("aditb002_lote_arquivos", (string)null);
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb001ControleArquivo", b =>
                {
                    b.HasOne("ControleArquivosGEADI.API.Models.Aditb002LoteArquivo", "NuLote")
                        .WithMany("Aditb001ControleArquivos")
                        .HasForeignKey("NuLoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NuLote");
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb002LoteArquivo", b =>
                {
                    b.Navigation("Aditb001ControleArquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
