// <auto-generated />
using System;
using ControleArquivosGEADI.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleArquivosGEADI.API.Migrations
{
    [DbContext(typeof(ControleDboContext))]
    [Migration("20250818131059_AddBaseMensalEtlTable")]
    partial class AddBaseMensalEtlTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb001ControleArquivo", b =>
                {
                    b.Property<long>("NuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("nu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NuId"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime>("DtLog")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_log");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_modificacao");

                    b.Property<string>("NoArquivo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("no_arquivo");

                    b.Property<string>("NoLocal")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("no_local");

                    b.Property<long>("NuLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("nu_lote_id");

                    b.Property<long>("QtBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("qt_bytes");

                    b.HasKey("NuId");

                    b.HasIndex("NuLoteId");

                    b.ToTable("aditb001_controle_arquivos", (string)null);
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb002LoteArquivo", b =>
                {
                    b.Property<long>("NuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("nu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NuId"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("QtArquivos")
                        .HasColumnType("int")
                        .HasColumnName("qt_arquivos");

                    b.HasKey("NuId");

                    b.ToTable("aditb002_lote_arquivos", (string)null);
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb003BaseMensalEtl", b =>
                {
                    b.Property<long>("NuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("nu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NuId"));

                    b.Property<string>("AmHonrado")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("am_honrado");

                    b.Property<string>("BaseCalculo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("base_calculo");

                    b.Property<string>("Cart")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cart");

                    b.Property<string>("CoAgRelac")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_ag_relac");

                    b.Property<string>("CoCart")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_cart");

                    b.Property<string>("CoMod")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_mod");

                    b.Property<string>("CoOpe")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_ope");

                    b.Property<string>("CoSeg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_seg");

                    b.Property<string>("CoSegad")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_segad");

                    b.Property<string>("CoSegger")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_segger");

                    b.Property<string>("CoSeggerGp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_segger_gp");

                    b.Property<string>("CoSis")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("co_sis");

                    b.Property<string>("CpfCnpj")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<string>("Ctr")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ctr");

                    b.Property<string>("DaAtual")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("da_atual");

                    b.Property<string>("DaIni")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("da_ini");

                    b.Property<string>("DdVencimentoContrato")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("DD_VENCIMENTO_CONTRATO");

                    b.Property<string>("DtConce")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("dt_conce");

                    b.Property<string>("DtMov")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("dt_mov");

                    b.Property<string>("IcAtacado")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ic_atacado");

                    b.Property<string>("IcCaixa")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ic_caixa");

                    b.Property<string>("IcHonrado")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ic_honrado");

                    b.Property<string>("IcReg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ic_reg");

                    b.Property<string>("IcRj")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ic_rj");

                    b.Property<string>("NoSeg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("no_seg");

                    b.Property<string>("NuTabelaAtual")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("nu_tabela_atual");

                    b.Property<string>("Posicao")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("posicao");

                    b.Property<string>("RatH5")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("rat_h5");

                    b.Property<string>("RatH6")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("rat_h6");

                    b.Property<string>("RatHh")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("rat_hh");

                    b.Property<string>("RatProv")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("rat_prov");

                    b.Property<string>("TpPessoa")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("tp_pessoa");

                    b.Property<string>("Unidade")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("unidade");

                    b.Property<string>("VlrConce")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vlr_conce");

                    b.HasKey("NuId");

                    b.ToTable("aditb003_base_mensal_ETL", (string)null);
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb001ControleArquivo", b =>
                {
                    b.HasOne("ControleArquivosGEADI.API.Models.Aditb002LoteArquivo", "NuLote")
                        .WithMany("Aditb001ControleArquivos")
                        .HasForeignKey("NuLoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NuLote");
                });

            modelBuilder.Entity("ControleArquivosGEADI.API.Models.Aditb002LoteArquivo", b =>
                {
                    b.Navigation("Aditb001ControleArquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
